name: ktor-swagger-issue-keycloak
services:
  keycloak:
    container_name: keycloak_unoptimized
    ports:
      - "8081:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=change_me
    volumes:
      - ./data:/opt/keycloak/data
    image: quay.io/keycloak/keycloak:latest
    command: start-dev